config/routes.rb
Rails.application.routes.draw do
  root to: 'stack#index'

  get ':page' => 'stack#show', as: 'stack'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stack_controller.rb
class StackController < ApplicationController
  before_action :chat_var
  layout :stack_layout
  def index; end

  def show()
    
    params[:page] = 'index' unless params[:page]
    # FAKE PARAMS
   
    render 'stack/'+ params[:page]
  end

  private
  def stack_layout
    
    if (params[:page] == 'login' or params[:page] == 'sign_up')
      return "blank"
    else
      return "application"
    end
  end
  
  def chat_var
    @chat = [{
      avatar: "256_rsz_1andy-lee-642320-unsplash.jpg",
      name: "Jenell D. Matney", 
      date: "4 days ago"
    }, {
      avatar: "256_daniel-gaffey-1060698-unsplash.jpg",
      name: "Sherri J. Cardenas", 
      date: "3 days ago"
    }, {
      avatar: "256_jeremy-banks-798787-unsplash.jpg",
      name: "Joseph S. Ferland", 
      date: "2 days ago"
    }, {
      avatar: "256_joao-silas-636453-unsplash.jpg",
      name: "Bryan K. Davis", 
      date: "1 day ago"
    }, {
      avatar: "256_luke-porter-261779-unsplash.jpg",
      name: "Elizabeth J. Ohara", 
      date: "4 hours ago"
    }, {
      avatar: "256_michael-dam-258165-unsplash.jpg",
      name: "Kaci M. Langston", 
      date: "just now"
    }]

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_drawer_left.html.erb
<div class="mdk-drawer js-mdk-drawer" id="default-drawer" data-align="start">
  <div class="mdk-drawer__content">
    <div class="sidebar sidebar-light sidebar-left simplebar" data-simplebar>
      <div class="sidebar-heading sidebar-m-t">Menu</div>
      <ul class="sidebar-menu">
        <li class="sidebar-menu-item <% if current_page?(root_path) || current_page?(stack_path(:index)) || current_page?(stack_path(:staff)) ||  current_page?(stack_path(:analytics)) %> active <% end %>">
          <a class="sidebar-menu-button" href="<%= root_path %>">
            <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">dvr</i>
            <span class="sidebar-menu-text">Dashboard</span>
          </a>
        </li>
        <li class="sidebar-menu-item <% if current_page?(stack_path(:ui_alerts))%>active<% end%>">
          <a class="sidebar-menu-button" href="<%= stack_path(:ui_alerts) %>">
            <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">dvr</i>
            <span class="sidebar-menu-text">Recruitment</span>
          </a>
        </li>
      </ul>
      <div class="sidebar-heading">UI Components</div>
      <div class="sidebar-block p-0">
        <ul class="sidebar-menu" id="components_menu">
          <li class="sidebar-menu-item <% if current_page?(stack_path(:ui_buttons))%>active<% end%>">
            <a class="sidebar-menu-button" href="<%= stack_path(:ui_buttons) %>">
              <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">mouse</i>
              <span class="sidebar-menu-text">Buttons</span>
            </a>
          </li>
          <li class="sidebar-menu-item <% if current_page?(stack_path(:ui_alerts))%>active<% end%>">
            <a class="sidebar-menu-button" href="<%= stack_path(:ui_alerts) %>">
              <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">notifications</i>
              <span class="sidebar-menu-text">Alerts</span>
            </a>
          </li>
          <li class="sidebar-menu-item <% if current_page?(stack_path(:ui_modals))%>active<% end%>">
            <a class="sidebar-menu-button" href="<%= stack_path(:ui_modals) %>">
              <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">aspect_ratio</i>
              <span class="sidebar-menu-text">Modals</span>
            </a>
          </li>
          <li class="sidebar-menu-item <% if current_page?(stack_path(:ui_icons))%>active<% end%>">
            <a class="sidebar-menu-button" href="<%= stack_path(:ui_icons) %>">
              <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">brush</i>
              <span class="sidebar-menu-text">Icons</span>
            </a>
          </li>
          <li class="sidebar-menu-item <% if current_page?(stack_path(:ui_forms))%>active<% end%>">
            <a class="sidebar-menu-button" href="<%= stack_path(:ui_forms) %>">
              <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">text_format</i>
              <span class="sidebar-menu-text">Forms</span>
            </a>
          </li>
          <li class="sidebar-menu-item <% if current_page?(stack_path(:ui_loaders))%>active<% end%>">
            <a class="sidebar-menu-button" href="<%= stack_path(:ui_loaders) %>">
              <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">refresh</i>
              <span class="sidebar-menu-text">Loaders</span>
            </a>
          </li>
          <li class="sidebar-menu-item <% if current_page?(stack_path(:ui_pagination))%>active<% end%>">
            <a class="sidebar-menu-button" href="<%= stack_path(:ui_pagination) %>">
              <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">last_page</i>
              <span class="sidebar-menu-text">Pagination</span>
            </a>
          </li>
        </ul>
      </div>
      <div class="sidebar-p-a">
        <a href="https://www.frontted.com/themes/stack-rails" class="btn btn-primary btn-block" target="_blank">Purchase PRO &dollar;99</a>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-main navbar-dark bg-dark pr-0" id="navbar" data-primary>
  <div class="container-fluid p-0">
    <!-- Navbar toggler -->
    <button class="navbar-toggler navbar-toggler-right d-block d-md-none" type="button" data-toggle="sidebar">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar Brand -->
    <a href="<%= root_path %>" class="navbar-brand">
      <span class="navbar-brand-icon">
       <svg xmlns="http://www.w3.org/2000/svg" width="25" height="26" viewBox="0 0 25 26">
        <g fill="none" fill-rule="evenodd" transform="translate(-4 -3)">
          <polygon points="0 0 33 0 33 33 0 33"/>
          <path fill="#4A90E2" d="M16.4861111,25.550603 L6.25,17.7383325 L4,19.4562139 L16.5,29 L29,19.4562139 L26.7361111,17.7246985 L16.4861111,25.550603 L16.4861111,25.550603 Z M16.5,22.0875721 L26.7222222,14.2753015 L29,12.5437861 L16.5,3 L4,12.5437861 L6.26388889,14.2753015 L16.5,22.0875721 L16.5,22.0875721 Z"/>
        </g>
      </svg>
      <span>Wellcode Base</span>
    </a>

    <ul class="nav navbar-nav ml-auto d-none d-md-flex">
      <li class="nav-item">
        <a href="https://www.frontted.com/contact" class="nav-link" target="_blank">
          <i class="material-icons">help_outline</i> Get Help
        </a>
      </li>
      <li class="nav-item mr-3">
        <a href="https://www.frontted.com/themes/stack-rails" class="btn btn-outline-warning" target="_blank">
          <i class="material-icons m  r-1">monetization_on</i> PURCHASE PRO
        </a>
      </li>
      <li class="nav-item dropdown">
        <a href="#" onClick="alert('Available in PRO version!')" class="nav-link dropdown-toggle" data-toggle="dropdown" data-caret="false">
          <i class="material-icons nav-icon navbar-notifications-indicator">notifications</i>
        </a>
      </li>
    </ul>

    <ul class="nav navbar-nav d-none d-sm-flex border-left navbar-height align-items-center">
      <li class="nav-item dropdown">
        <a href="#account_menu" class="nav-link dropdown-toggle" data-toggle="dropdown" data-caret="false">
          <img src="<%= image_path('')%>" class="rounded-circle" width="32" alt="Eweuh Goblok!">
          <span class="ml-1 d-flex-inline">
            <span class="text-light">Khairul Anwar</span>
          </span>
        </a>
        <div id="account_menu" class="dropdown-menu dropdown-menu-right">
          <div class="dropdown-item-text dropdown-item-text--lh">
            <div><strong>Khairul Anwar</strong></div>
            <div>@khairulanwar</div>
          </div>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="<%= root_path %>">Dashboard</a>
          <a class="dropdown-item" href="#" onClick="alert('Available in PRO version!')"> My profile</a>
          <a class="dropdown-item" href="#"  onClick="alert('Available in PRO version!')" >Edit account</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#"  onClick="alert('Available in PRO version!')" >Logout</a>
        </div>
      </li>
    </ul>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title> Wellcode Portal Admin </title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= @body_class || 'layout-default' %>">
    <!-- Header Layout -->
    <div class="mdk-header-layout js-mdk-header-layout">

      <!-- Header -->
      <div id="header" class="mdk-header js-mdk-header m-0" data-fixed>
        <div class="mdk-header__content">
          <%= render 'layouts/navbar'%>
        </div>
      </div>
      <!-- // END Header -->

      <!-- Header Layout Content -->
      <div class="mdk-header-layout__content">

        <div class="mdk-drawer-layout js-mdk-drawer-layout" data-push data-responsive-width="992px">
          <div class="mdk-drawer-layout__content page">
            <%# CONTENT  %>
            <%= yield %>
          </div>
          <!-- // END drawer-layout__content -->

          <%= render 'layouts/drawer_left' %>
        </div>
        <!-- // END drawer-layout -->

      </div>
      <!-- // END header-layout__content -->

    </div>
    <!-- // END header-layout -->

    <%= content_for :footer %>

    <%= javascript_include_tag 'core-scripts', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= content_for :footer_scripts %>
  </body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Stack-Rails - Rails 5 &amp; Bootstrap 4 Admin Dashboard</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

<body class="<%= @body_class || 'layout-fluid' %>">

  <%= yield %>

</body>
</html>

app/views/stack/_pagination.html.erb
<%
  pages = pages || 2
  first = first || false
  prevItem = prevItem || true
  nextItem = nextItem || true
  last = last || false
  labels = labels || false
  align = align || 'left'
  className= className || ''
%>
<ul class="pagination<% if align == 'center' %> justify-content-center<% end %><% if align == 'right' %> justify-content-end<% end %><%= className %>">
  <% if first %>
  <li class="page-item disabled">
    <a class="page-link" href="#" aria-label="Previous">
      <span aria-hidden="true" class="material-icons">first_page</span>
      <span<% if labels.blank? %> class="sr-only"<% end %>>First</span>
    </a>
  </li>
  <% end %>
  <% if prevItem %>
  <li class="page-item disabled">
    <a class="page-link" href="#" aria-label="Previous">
      <span aria-hidden="true" class="material-icons">chevron_left</span>
      <span<% if labels.blank? %> class="sr-only"<% end %>>Prev</span>
    </a>
  </li>
  <% end %>
  <% (0..pages-1).each do |i| %>
    <li class="page-item<% if i == 0 %> active<% end %>">
      <a class="page-link" href="#" aria-label="<%= i+1 %>">
        <span><%= i+1 %></span>
      </a>
    </li>
  <% end %>
  <% if nextItem %>
  <li class="page-item">
    <a class="page-link" href="#" aria-label="Next">
      <span<% if labels.blank? %> class="sr-only"<% end %>>Next</span>
      <span aria-hidden="true" class="material-icons">chevron_right</span>
    </a>
  </li>
  <% end %>
  <% if last.present? %>
  <li class="page-item">
    <a class="page-link" href="#" aria-label="Next">
      <span<% if labels.blank? %> class="sr-only"<% end %>>Last</span>
      <span aria-hidden="true" class="material-icons">last_page</span>
    </a>
  </li>
  <% end %>
</ul>

app/views/stack/index.html.erb
<div class="container-fluid page__heading-container">
  <div class="page__heading d-flex align-items-center">
    <div class="flex">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb mb-0">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
        </ol>
      </nav>
      <h1 class="m-0">Rails 5 <span class="text-primary">FREE</span> Admin Theme</h1>
    </div>
  </div>
</div>

<div class="container-fluid page__container">

  <div class="card">
  <div class="card-body">
    <h4>Rails 5 Free Admin Theme</h4>
    <p>Stack Rails Base is a Free Rails Bootstrap 4 Admin Theme covering the basic needs of an Admin Application from layout to components.</p>

    <a class="btn btn-success mr-2" href="http://www.frontted.com/themes/stack-rails-base">
      <i class="material-icons align-middle">file_download</i> Download FREE
    </a>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
    
    <div class="d-flex justify-content-between align-items-center">
    <h4 class="mb-0"><span class="text-muted">[PRO]</span> Stack Rails Admin Dashboard Theme</h4>
    <a class="btn btn-primary ml-2 float-right" href="http://www.frontted.com/themes/stack-rails" target="_blank">
      <i class="material-icons align-middle">shopping_cart</i> Purchase PRO: $99
    </a>
    </div>
    <hr>
    <ul>
      <li>Included All of Bootstrap 4.1 Components</li>
      <li>3x Dashboards</li>
      <li>4+ Application Interfaces</li>
      <li>Customized Line, Bar, Area &amp; Donut Charts</li>
      <li>Projects, Trello (drag &amp; drop), Chat &amp; Calendar Apps</li>
      <li>10+ stats card variants</li>
      <li>5+ list card variants</li>
      <li>Forms:

        <ul>
        <li>Validation</li>
        <li>Search</li>
        <li>Group</li>
        <li>Rounded</li>
        <li>Flush</li>
        <li>Toggle</li>
        <li>Date pickers</li>
        <li>Input Masking</li>
        <li>WYSIWYG editor</li>
        <li>File Uploads with drag and drop</li>
        <li>Select2 Plugin</li>
        </ul>
      </li>
      <li>Navbar with buttons, menu, forms, avatars, and more!</li>
      <li>Light/Dark Sidebar Styles</li>
      <li>Material &amp; Font Awesome Icons</li>
      <li>Calendar App with drag &amp; drop events</li>
      <li>Functional listing search with list.js</li>
      <li>Extended/Customized Vector Maps</li>
      </ul>
      <hr>
      <div class="text-center">
        <a class="btn btn-secondary btn-lg mr-2" href="https://stack-rails.herokuapp.com/stack/index" target="_blank">
          Live Preview
        </a>
      </div>
  </div>
</div>
</div>

app/views/stack/ui_alerts.html.erb
<div class="container-fluid page__heading-container">
  <div class="page__heading">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="#"><i class="material-icons icon-20pt">home</i></a></li>
        <li class="breadcrumb-item">UI Components</li>
        <li class="breadcrumb-item active" aria-current="page">Alerts</li>
      </ol>
    </nav>
    <h1 class="m-0">Alerts</h1>
  </div>
</div>

<div class="container-fluid page__container">
  <div class="card">
    <div class="card-header card-header-large bg-white">
      <h4 class="card-header__title">Toast</h4>
    </div>
    <div class="card-body">
      <p>Toasts based notifications can be used to to show important alerts or information to users.</p>
      <a href="https://stack-rails.herokuapp.com/stack/ui_alerts" class="btn btn-primary" target="_blank">Available in PRO</a>
    </div>
  </div>
  <div class="row">
    <div class="col-lg">
      <div class="card">
        <div class="card-header card-header-large bg-white">
          <h4 class="card-header__title">Alerts</h4>
        </div>
        <div class="card-body">
          <p>Alerts are available for any length of text, as well as an optional dismiss button. For proper styling, use one of the eight contextual classes (i.e. <code>.alert-success</code>). For background color use class <code>.bg-*</code> and <code>.text-white</code>.</p>

          <div class="alert alert-primary" role="alert">
            <strong>Primary - </strong> A simple primary alert - check it out!
          </div>
          <div class="alert alert-secondary" role="alert">
            <strong>Secondary - </strong> A simple secondary alert - check it out!
          </div>
          <div class="alert alert-success" role="alert">
            <strong>Success - </strong> A simple success alert - check it out!
          </div>
          <div class="alert alert-danger" role="alert">
            <strong>Danger - </strong> A simple danger alert - check it out!
          </div>
          <div class="alert alert-warning" role="alert">
            <strong>Warning - </strong> A simple warning alert - check it out!
          </div>
          <div class="alert alert-info" role="alert">
            <strong>Info - </strong> A simple info alert - check it out!
          </div>
          <div class="alert alert-light" role="alert">
            <strong>Light - </strong> A simple light alert - check it out!
          </div>
          <div class="alert alert-dark" role="alert">
            <strong>Dark - </strong> A simple dark alert - check it out!
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg">
      <div class="card">
        <div class="card-header card-header-large bg-white">
          <h4 class="card-header__title">Dismissible Alerts</h4>
        </div>
        <div class="card-body">
          <p>Add a button and the <code>.alert-dismissible</code> class, which adds extra padding to the right of the alert and positions the <code>.close</code> button.</p>

          <div class="alert alert-dismissible bg-primary text-white border-0 fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong>Primary - </strong> A simple primary alert - check it out!
          </div>

          <div class="alert alert-dismissible bg-secondary text-white border-0 fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong>Secondary - </strong> A simple secondary alert - check it out!
          </div>

          <div class="alert alert-dismissible bg-success text-white border-0 fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong>Success - </strong> A simple success alert - check it out!
          </div>

          <div class="alert alert-dismissible bg-danger text-white border-0 fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong>Danger - </strong> A simple danger alert - check it out!
          </div>

          <div class="alert alert-dismissible bg-warning text-white border-0 fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong>Warning - </strong> A simple warning alert - check it out!
          </div>

          <div class="alert alert-dismissible bg-info text-white border-0 fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong>Info - </strong> A simple info alert - check it out!
          </div>

          <div class="alert alert-dismissible bg-light border-0 fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong>Light - </strong> A simple light alert - check it out!
          </div>

          <div class="alert alert-dismissible bg-dark text-white border-0 fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong>Dark - </strong> A simple dark alert - check it out!
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header card-header-large bg-white">
      <h4 class="card-header__title">Soft Alerts</h4>
    </div>
    <div class="card-body">
      <p>Alternate styles for alerts with softer background color by replacing classes like <code>.alert-primary</code> with <code>.alert-soft-primary</code>. Alerts can also contain additional HTML elements like icons and paragraphs.</p>

      <a href="https://stack-rails.herokuapp.com/stack/ui_alerts" class="btn btn-primary" target="_blank">Available in PRO</a>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-header card-header-large bg-white">
          <h4 class="card-header__title">Badges</h4>
        </div>
        <div class="card-body">
          <p>A small count and labeling component. Please read the <a href="https://getbootstrap.com/docs/4.1/components/badge/" target="_blank">official Bootstrap documentation</a> for a full list of options.</p>

          <span class="badge badge-primary">Primary</span>
          <span class="badge badge-secondary">Secondary</span>
          <span class="badge badge-success">Success</span>
          <span class="badge badge-danger">Danger</span>
          <span class="badge badge-warning">Warning</span>
          <span class="badge badge-info">Info</span>
          <span class="badge badge-light">Light</span>
          <span class="badge badge-dark">Dark</span><br>
          <span class="badge badge-pill badge-primary">Primary</span>
          <span class="badge badge-pill badge-secondary">Secondary</span>
          <span class="badge badge-pill badge-success">Success</span>
          <span class="badge badge-pill badge-danger">Danger</span>
          <span class="badge badge-pill badge-warning">Warning</span>
          <span class="badge badge-pill badge-info">Info</span>
          <span class="badge badge-pill badge-light">Light</span>
          <span class="badge badge-pill badge-dark">Dark</span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stack/ui_loaders.html.erb
<div class="container-fluid page__heading-container">
  <div class="page__heading">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="#"><i class="material-icons icon-20pt">home</i></a></li>
        <li class="breadcrumb-item">UI Components</li>
        <li class="breadcrumb-item active" aria-current="page">Loaders</li>
      </ol>
    </nav>
    
    <h1 class="m-0">Loaders</h1>
  </div>
</div>

<div class="container-fluid page__container">
  <div class="row">
    <div class="col-lg">
      <div class="card">
        <div class="card-header card-header-large bg-white">
          <h4 class="card-header__title">Sizes</h4>
        </div>
        <div class="card-body">
          <p>A simple yet versatile animated spinner component. Add <code>.loader-[sm|lg]</code> or <code>.is-loading-[sm|lg]</code> to create loaders at different sizes.</p>
          <div class="loader-list">
            <div class="loader loader-lg"></div>
            <div class="loader"></div>
            <div class="loader loader-sm"></div>
          </div>
        </div>
      </div>

      <h4>Loader Helper</h4>
      <p>Indicate loading state of nearly any component with an <code>.is-loading</code> modifier.</p>

      <div class="card">
        <div class="card-header card-header-large bg-white">
          <h4 class="card-header__title">Loading card</h4>
        </div>
        <div class="card-body is-loading is-loading-lg">
          Loading content
        </div>
      </div>

      <div class="button-list">
        <a href="#" class="btn btn-lg btn-primary is-loading">Button</a>
        <a href="#" class="btn btn-outline-primary is-loading is-loading-sm">Button</a>
      </div>
    </div>
    <div class="col-lg">
      <div class="card">
        <div class="card-header card-header-large bg-white">
          <h4 class="card-header__title">Colors</h4>
        </div>
        <div class="card-body">
          <p>Using Bootstrap’s typical naming structure i.e. <code>.loader-primary</code>, you can create colored loaders depending on your needs.</p>

          <div class="loader-list">
            <div class="loader loader-primary"></div>
            <div class="loader loader-secondary"></div>
            <div class="loader loader-success"></div>
            <div class="loader loader-danger"></div>
            <div class="loader loader-warning"></div>
            <div class="loader loader-info"></div>
            <div class="loader loader-dark"></div>
            <div class="loader loader-light"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stack/ui_pagination.html.erb
<div class="container-fluid page__heading-container">
  <div class="page__heading">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="#"><i class="material-icons icon-20pt">home</i></a></li>
        <li class="breadcrumb-item">UI Components</li>
        <li class="breadcrumb-item active" aria-current="page">Pagination</li>
      </ol>
    </nav>
    
    <h1 class="m-0">Pagination</h1>
  </div>
</div>

<div class="container-fluid page__container">
  <div class="row">
    <div class="col-lg">
      <div class="card card-body">
        // content above this line
        <hr>
        <div class="d-flex flex-row align-items-center">
          <div class="form-inline">
            View 
            <select class="custom-select ml-2" style="width: 70px;">
              <option value="20" selected>20</option>
              <option value="50">50</option>
              <option value="100">100</option>
              <option value="200">200</option>
            </select>
          </div>
          <div class="ml-auto">
            20 <span class="text-muted">of 100</span> <a href="#" class="icon-muted"><i class="material-icons float-right">arrow_forward</i></a>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header card-header-large bg-white">
          <h4 class="card-header__title">Pagination Light</h4>
        </div>
        <div class="card-body">
          <div class="pagination-light">
            <%= render 'pagination', pages: 4, first: true, last: true %>
            <%= render 'pagination', pages: 2, labels: true, class: "m-0" %>
          </div>
        </div>
      </div>
      <div class="card">
          <div class="card-header card-header-large bg-white">
            <h4 class="card-header__title">Pagination Square</h4>
          </div>
          <div class="card-body">
           <%= render 'pagination', pages: 4, first: true, last: true %>
            <%= render 'pagination', pages: 2, labels: true, class: "m-0" %>
          </div>
        </div>
      <div class="card">
        <div class="card-header card-header-large bg-white">
          <h4 class="card-header__title">Pagination Rounded</h4>
        </div>
        <div class="card-body">
          <div class="pagination-rounded">
             <%= render 'pagination', pages: 4, first: true, last: true %>
            <%= render 'pagination', pages: 2, labels: true, class: "m-0" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>